-- PROJETO DOMAIN DRIVE DESING / CP: V
-- API de Cadastro de Coleções e Cartas com JAX-RS e Log4j
DROP TABLE POKEMON_CARDS;
DROP TABLE POKEMON_COLLECTION;

CREATE TABLE POKEMON_COLLECTION (
    COLLECTION_ID NUMBER GENERATED AS IDENTITY CONSTRAINT COLLECTION_PK PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000)
);

CREATE TABLE POKEMON_CARDS (
    CARD_ID NUMBER GENERATED AS IDENTITY CONSTRAINT CARDS_PK PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    CATEGORY VARCHAR2(255) NOT NULL,
    TYPE VARCHAR2(255) NOT NULL,
    HEALTH NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    COLLECTION_ID NUMBER
);

ALTER TABLE POKEMON_CARDS ADD CONSTRAINT CARD_COLLECTION_FK FOREIGN KEY(COLLECTION_ID) REFERENCES POKEMON_COLLECTION (COLLECTION_ID);

INSERT INTO POKEMON_COLLECTION (NAME, DESCRIPTION) VALUES ('Coleções', 'Descrição');
INSERT INTO POKEMON_CARDS (NAME, CATEGORY, TYPE, HEALTH, DESCRIPTION, COLLECTION_ID) VALUES ('Cartas', 'Categorias', 'Tipos', 0, 'Descrição', 1);
COMMIT;

SELECT * FROM POKEMON_COLLECTION;
SELECT * FROM POKEMON_CARDS;

